"""inital migration

<<<<<<<< HEAD:server/migrations/versions/e201c7bebfe2_initial.py
Revision ID: e201c7bebfe2
Revises: 
Create Date: 2023-11-29 18:07:55.434056
========
Revision ID: 0c7f0c1347e8
Revises: 
Create Date: 2023-11-29 17:35:11.875115
>>>>>>>> main:server/migrations/versions/0c7f0c1347e8_inital_migration.py

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
<<<<<<<< HEAD:server/migrations/versions/e201c7bebfe2_initial.py
revision = 'e201c7bebfe2'
========
revision = '0c7f0c1347e8'
>>>>>>>> main:server/migrations/versions/0c7f0c1347e8_inital_migration.py
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('date', sa.String(), nullable=True),
    sa.Column('time', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('details', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('_password_hash', sa.String(), nullable=False),
    sa.Column('gender', sa.String(), nullable=False),
    sa.Column('preference', sa.String(), nullable=False),
    sa.Column('profile_picture', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('location_range', sa.Integer(), nullable=True),
    sa.Column('bio', sa.String(), nullable=True),
    sa.Column('interests', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('connections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name=op.f('fk_connections_event_id_events')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_connections_user_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_connections',
    sa.Column('user1', sa.Integer(), nullable=False),
    sa.Column('user2', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user1'], ['users.id'], name=op.f('fk_user_connections_user1_users')),
    sa.ForeignKeyConstraint(['user2'], ['users.id'], name=op.f('fk_user_connections_user2_users')),
    sa.PrimaryKeyConstraint('user1', 'user2')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_connections')
    op.drop_table('connections')
    op.drop_table('users')
    op.drop_table('events')
    # ### end Alembic commands ###
