"""add circular

Revision ID: 154cb58688a3
Revises: 043986eb06ba
Create Date: 2023-11-29 19:39:18.738430

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '154cb58688a3'
down_revision = '043986eb06ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_connections',
    sa.Column('user1', sa.Integer(), nullable=False),
    sa.Column('user2', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user1'], ['users.id'], name=op.f('fk_user_connections_user1_users')),
    sa.ForeignKeyConstraint(['user2'], ['users.id'], name=op.f('fk_user_connections_user2_users')),
    sa.PrimaryKeyConstraint('user1', 'user2')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('swiped')
        batch_op.drop_column('rejected')
        batch_op.drop_column('friends')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('friends', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('rejected', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('swiped', sa.VARCHAR(), nullable=True))

    op.drop_table('user_connections')
    # ### end Alembic commands ###
